sudo: required
dist: trusty

git:
  depth: 5

before_deploy:
- sudo apt-get update -qq
- sudo apt-get install -qq subversion

deploy:
  skip_cleanup: true
  provider: script
  script: deploy/deploy.sh

env:
  global:
  - secure: AcQ0NqbQMyhBkFkLXoXo5f++2KlT7+3ICdXRkiG8h07BpoelN4zoRAQTSPJIaKetLwdNJjY6+bLR6ZeQP3CQxKfectpXZBU3b7Ae5MqP773DoOe3cRtm5Ns0PtePI/I5XWZc5rOaCXB6ax5wn+bVqPlX0ercensU0z+EGgpSEAkAnblAvT2btHzO2IJOHEYe2OUgsHHjHShkNhF2fcPS0T8kCkDUX79D4BzPSkro3SL4JfvTBUOThIHVLYivjvCNOhAhqVCKow5ykR1yKoUYF8uvbsSR6HTuZpSxOpRgy8+gD24RZ56pTsF9krK33uSFhHWRl/+j2jVztKquT9np0/fuaFbNzmIwyX7gf87qhyvBebzvEiAgFDGK8Fs47uA5S+xx1sWGL02BkCIyQZz88VAgmCBxf6Y9kf9YcKWKMMwzs9Q9PGzlDRMfK80iR21ddbxdjD0LtyCSMFrQ70J99F25MWKOyE8MJcB3DqEUhOcZcdvFg1gkGmNzaP57tUukEXNNsyJWfir2xcDKecZiiG6llqo6uQaoqk2r/QhKghuulMZpcudnYpGhkpiFDoF5pq0jp92R6AS24Ps+9YGthIVA07sZHsJDLbthZLlrTkB4FGFSEvisi/A18dDt9ijAX9U6257QSzJuYjbKgeXQcY3g0yGzwgTpLWad5NIqgp8=
  - secure: wtrOJumA5z1CZ9bl7/fcETviHNd42KgZdrm26PYagFK49vGPbw33iodBEun+jhpmHLCZjztiJ611o2oKPpZCsL2z6HNaXdQHxwmsYkI8bbHROp7GgQAJ/jnrE3//v3oiAd5pWlWWdz5jxbv3ZGDlm4OHcF+ZYAGlYQNYjT6tppu67ggkw+yT5gIONq84hnNRb9Vh3LNs17nzVsmjDVIEp4u/ofJbqpjjuLwPnjK5yz/uSj5ZbSwMD06U/QTj6dCRdA80DOuVALqPrOHf5sIhSHKJLsATY632Kyi6ihpHExLq1sk7Xs3R/kHp9RpzMXflXc8Ald9BZdEEXSZKfWnFxPGyy4AtRGtxA79qQ8pbr+c5LDiKy4Dsh+KAefZIbocbM7x/gkz2r2VCz9oF41DrQWw3Cc3r6tv0NiwKumUlGfrPLM1KFdHctGNITBNyneUwktWKBFkXWTQTaSuTkfEqXOyeFvKC3G01GHewDFtuZ7bqbgJv/U9kII71WmiEYzDVaoWBOD1H1k1WKc1JekKDg4pVYwDqIp9mONPlFEsJ7TR5pvulH4zmVkJUBUKcUGqJZKMHbNCCh+cVIcnIVGxPb5vcvFEbYpXqaHTKf+re7KnXgLBYjehiQx4AgqrlrIWKhqc2vvK9lfcZNNFELndE3F7K1s8HDHhDINlLZMK5eRA=

