dist: trusty
language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
branches:
  only:
  - master
  - "/^\\d\\.\\d\\.\\d(?: revision \\d)?$/"
before_install:
  - export PHPCS_DIR=/tmp/phpcs
  - export PHPCS_REPO=https://github.com/squizlabs/PHP_CodeSniffer.git
  - export WPCS_DIR=/tmp/sniffs
  - export WPCS_REPO=https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  - git clone -b master $PHPCS_REPO $PHPCS_DIR
  - git clone -b master $WPCS_REPO $WPCS_DIR
  - $PHPCS_DIR/bin/phpcs --config-set installed_paths $WPCS_DIR
script:
  - php -l *.php
  - $PHPCS_DIR/bin/phpcs --standard=WordPress-Extra --extensions=php .
deploy:
  skip_cleanup: true
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
    php: 7.3
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/inline-spoilers/
  - secure: ptaeITxYtBZH8dww0hB0CRapfGrMEEHStxkWMdVWVsE17Lss/jZbjOHT/6/Jix4EHMQOSGJKLR5Asp9ZLkeoHpia65RhmaIN4lPCPP2KM4T6trq9tpKhtGTU6YEyIxbwgHz34NuAwZWVbUFXLtY9YUpN9ffWbG5AhPyn4nRi7wOOwKpGCtbw1KF4dhHH/r64ZKDUqu5ki0ZQR4J2gJnzKQfyTQafQN7yHy9soEWch++22zjHqmmoFH/ot/LLyZ425lIMtWEdFn3+tz21blxIpaM3Lk2QRBmTo73FzoK06N5XvpIs+XuHjuAZBUyFJ1vzOqUPnhdDy0bMhKRA1C5+/yYlf1llftVJHVM/c5VWUbeMbxswtZZJBysmh/xC19bFkumoQwgNgcww9pl9XJESXS2t05X3PToY3IW/zO/H32p2lh25p0RdXKEwCK8y9g4iW05KEULEBP/3NDBqaSSAqr8soy1SjOrQyENhv6MU+MQV4skAvhZNQQ3CQs4I9lvtW/0jJPKiWai87RA+TvL1b3KCiWxEcskTTa/FSEdv5UN77MWKHbcY9XHthy9PK7EoMXTNHOxkPaismonav6X7z1DcRo+bBl1VL0NX230pNh1BGQqPJr9zLhaGUQdb71X+R1RdcALeST83j2p00ZsRIPK37JlyPFSQvgyEq+Yp678=
  - secure: i3lms2SI0frg9o25h4wWug+kzB5oYdyflcWWhxmUr2FgnTvviTpzdPCVV8SPQreDVS6eJSm7HJTRowRnbLRmX/2IJErOgXiu/EU7ALmVfg3msFZ2+/sXE4CJr1mmXivNQXOezcJkNklXzxUGbVXhFTCp3Hb3a4eIvXTLE5JnFC2MN2iBqH1P0ySmnQjObSNwfCkiVOGXKh2gGYamE9idsUaPzSnZ+cc3det4BZ4cZpdSwbD6V5BfBlp0vUXRLajXWXSd4c8NMRf0ZM/vd6ojKAc5GS/FeNEL9FlAiQ2fH4f53qDHCBfw4kl+ALIFoWWb3icFNqlT1/g8DLM7JxxcFbotjCqNBU5qc3XOo+4ix7RlqH6ZsSImzbnQqqVNU3AASEFAoxtBSfeggT4MprHQIcNdDUBNI0GcZZxg1tsr4LkQ8BUqOnZc4w6Q+f/s8LlB4eF/InBNgboCOTWfR3epGrvFZ/S632xeaXiss+FEOfQN5UkYPrAGjEP+EeTjnAxSZl69PNMrmBA9jESLDnAnAava4xFJJXfj7UdncbI7iwWaPOgsnEgmqB/DgfsQDfnokafgs0wCoyQy/JBELos1WGiTGF99EtLhV+1dKUg/3yH9tiKhUOyQlDqa9bXLdygxF94oubp3HYgttglMjClnYKr7knB1EQTYXFpu7n83ii4=
